# Generated by Django 3.2.16 on 2022-10-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('work_type', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('skills', models.ManyToManyField(related_name='registers', to='app.Skills')),
            ],
        ),
    ]
