# Generated by Django 3.2.16 on 2022-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221017_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_type',
            field=models.CharField(choices=[('part_time', 'part_time'), ('Full_time', 'Full_time')], max_length=30),
        ),
    ]
